"""Communication Agent — Week 5 specialist.

Handles all outbound communication with claimants:
- Requesting missing documents
- Sending approval/rejection notifications
- Generating plain-language settlement explanations

Pattern: same tool-binding pattern as FraudAgent and CoverageAgent.
Week 5: integrate with supervisor.py multi-agent coordinator.
"""
from __future__ import annotations

from typing import Any

from langchain_google_genai import ChatGoogleGenerativeAI

from agent.tools.claim_tools import request_missing_document
from config.settings import get_settings


class CommunicationAgent:
    """Specialist agent for claimant-facing communications.

    Responsibilities:
    - Draft and send document request notices
    - Generate settlement / rejection letters
    - Maintain communication thread audit trail

    Week 5 implementation:
    - Binds request_missing_document tool
    - LLM generates plain-language explanations from claim state
    - All outputs pass through SafetyJudge before sending
    """

    TOOLS = [request_missing_document]

    SYSTEM_PROMPT = (
        "You are an insurance communication specialist. "
        "Your job is to draft clear, professional, empathetic communications "
        "to claimants. You MUST:\n"
        "1. Never include PII (Aadhaar, PAN, phone, email, address) in communications\n"
        "2. Use plain language — no insurance jargon without explanation\n"
        "3. Always state the specific document needed and why\n"
        "4. Include a reference ID (claim_id) in every communication\n"
        "5. Set a clear deadline for document submission"
    )

    def __init__(self, llm: ChatGoogleGenerativeAI | None = None) -> None:
        settings = get_settings()
        self.llm = llm or ChatGoogleGenerativeAI(
            model=settings.gemini_model,
            temperature=0.3,   # slightly creative for professional tone
            google_api_key=settings.google_api_key or None,
        )

    def request_documents(
        self,
        claim_id: str,
        missing_docs: list[str],
        reason: str,
    ) -> dict[str, Any]:
        """Log document requests and draft claimant notice.

        Args:
            claim_id: Claim identifier
            missing_docs: List of required document types
            reason: Why documents are needed

        Returns:
            Dict with request_ids and drafted notice text
        """
        results = []
        for doc_type in missing_docs:
            result = request_missing_document.invoke({
                "claim_id": claim_id,
                "document_type": doc_type,
                "reason": reason,
            })
            results.append(result)

        # Week 5: LLM drafts a plain-language notice from the results
        notice = (
            f"[STUB] Document request notice for {claim_id}: "
            f"Please submit {', '.join(missing_docs)} within 14 days. "
            f"Reason: {reason}"
        )
        return {
            "claim_id": claim_id,
            "documents_requested": missing_docs,
            "tool_results": results,
            "drafted_notice": notice,
        }

    def draft_decision_letter(
        self,
        claim_id: str,
        decision: str,
        settlement_amount: float,
        policy_citations: list[str],
    ) -> str:
        """Draft a decision letter for the claimant.

        Week 5: LLM generates full letter from structured inputs.
        SafetyJudge validates output before returning.

        Args:
            claim_id: Claim identifier
            decision: 'approved', 'rejected', or 'partial'
            settlement_amount: Settlement amount in INR (0 if rejected)
            policy_citations: Policy clauses supporting the decision

        Returns:
            Plain-text decision letter (PII-free)
        """
        # Week 5: full LLM generation + SafetyJudge validation
        return (
            f"[STUB] Decision Letter — Claim {claim_id}\n"
            f"Decision: {decision.upper()}\n"
            f"Settlement: Rs {settlement_amount:,.0f}\n"
            f"Based on: {'; '.join(policy_citations) if policy_citations else 'policy terms'}\n"
            f"[Full letter generated by LLM in Week 5]"
        )
